import React, { createContext, useContext, useState, useEffect } from 'react';
import { SUPPORTED_LANGUAGES, type LanguageConfig, t as tI18n, type TranslationKey } from '../i18n';

interface LanguageContextType {
  currentLanguage: string;
  setLanguage: (code: string) => void;
  languageConfig: LanguageConfig;
  t: (key: any) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const UI_DICTIONARIES: Record<string, Record<string, string>> = {
  "en": {
    "Dashboard": "Dashboard",
    "Official Command Center": "Official Command Center",
    "Command Center": "Command Center",
    "Groundwater Map": "Groundwater Map",
    "Forecast & Predictions": "Forecast & Predictions",
    "Anomalies & Triage": "Anomalies & Triage",
    "Anomaly Detection": "Anomaly Detection",
    "Crop & Irrigation Advice": "Crop & Irrigation Advice",
    "Crop Advisor": "Crop Advisor",
    "Regional Analytics": "Regional Analytics",
    "WhatsApp AI Assistant": "WhatsApp AI Assistant",
    "WhatsApp Farmer": "WhatsApp Farmer",
    "Help & Knowledge Base": "Help & Knowledge Base",
    "Help & Knowledge": "Help & Knowledge",
    "Officer Login Portal": "Officer Login Portal",
    "Navigation": "Navigation",
    "DWLR Telemetry Network": "DWLR Telemetry Network",
    "Real-Time DWLR Groundwater Intelligence": "Real-Time DWLR Groundwater Intelligence",
    "Switch Account / Role": "Switch Account / Role",
    "Explore Groundwater Map": "Explore Groundwater Map",
    "Get Crop Advice": "Get Crop Advice",
    "View Technical Evidence": "View Technical Evidence",
    "Executive Water Intelligence Brief": "Executive Water Intelligence Brief",
    "Current Situation": "Current Situation",
    "Priority Risk Belt": "Priority Risk Belt",
    "30-Day Forecast": "30-Day Forecast",
    "Recommended Action": "Recommended Action",
    "Regional Stress Level": "Regional Stress Level",
    "Critical Stations": "Critical Stations",
    "Recharge Outlook": "Recharge Outlook",
    "Confidence Score": "Confidence Score",
    "Data Provenance": "Data Provenance",
    "login": "Login",
    "logout": "Sign Out"
  },
  "hi": {
    "Dashboard": "डैशबोर्ड",
    "Official Command Center": "आधिकारिक कमांड सेंटर",
    "Command Center": "कमांड सेंटर",
    "Groundwater Map": "भूजल मानचित्र",
    "Forecast & Predictions": "पूर्वानुमान",
    "Anomalies & Triage": "जोखिम चेतावनी",
    "Anomaly Detection": "असामान्य गिरावट",
    "Crop & Irrigation Advice": "फसल एवं सिंचाई सलाह",
    "Crop Advisor": "फसल सलाहकार",
    "Regional Analytics": "क्षेत्रीय विश्लेषण",
    "WhatsApp AI Assistant": "व्हाट्सएप एआई सहायक",
    "WhatsApp Farmer": "व्हाट्सएप किसान सेवा",
    "Help & Knowledge Base": "सहायता केंद्र",
    "Help & Knowledge": "सहायता व स्रोत",
    "Officer Login Portal": "अधिकारी लॉगिन पोर्टल",
    "Navigation": "नेविगेशन",
    "DWLR Telemetry Network": "डीडब्ल्यूएलआर टेलीमेट्री नेटवर्क",
    "Real-Time DWLR Groundwater Intelligence": "रीयल-टाइम भूजल बुद्धिमत्ता",
    "Switch Account / Role": "खाता / भूमिका बदलें",
    "Explore Groundwater Map": "भूजल मानचित्र देखें",
    "Get Crop Advice": "फसल सलाह प्राप्त करें",
    "View Technical Evidence": "तकनीकी प्रमाण देखें",
    "Executive Water Intelligence Brief": "कार्यकारी जल खुफिया संक्षिप्त",
    "Current Situation": "वर्तमान स्थिति",
    "Priority Risk Belt": "प्राथमिकता जोखिम क्षेत्र",
    "30-Day Forecast": "30-दिवसीय पूर्वानुमान",
    "Recommended Action": "अनुशंसित कार्रवाई",
    "Regional Stress Level": "क्षेत्रीय तनाव स्तर",
    "Critical Stations": "गंभीर स्टेशन",
    "Recharge Outlook": "रिचार्ज आउटलुक",
    "Confidence Score": "विश्वास स्कोर",
    "Data Provenance": "डेटा स्रोत",
    "login": "लॉग इन",
    "logout": "साइन आउट"
  },
  "bn": {
    "Dashboard": "ড্যাশবোর্ড",
    "Official Command Center": "অফিসিয়াল কমান্ড সেন্টার",
    "Command Center": "কমান্ড সেন্টার",
    "Groundwater Map": "ভূগর্ভস্থ জল মানচিত্র",
    "Forecast & Predictions": "পূর্বাভাস ও অনুমান",
    "Anomalies & Triage": "ঝুঁকি ও সতর্কতা",
    "Anomaly Detection": "অস্বাভাবিক পতন সনাক্তকরণ",
    "Crop & Irrigation Advice": "ফসল ও সেচ পরামর্শ",
    "Crop Advisor": "ফসল উপদেষ্টা",
    "Regional Analytics": "আঞ্চলিক বিশ্লেষণ",
    "WhatsApp AI Assistant": "হোয়াটসঅ্যাপ এআই সহকারী",
    "WhatsApp Farmer": "হোয়াটসঅ্যাপ কৃষক সেবা",
    "Help & Knowledge Base": "সাহায্য ও তথ্য কেন্দ্র",
    "Help & Knowledge": "সাহায্য ও তথ্য",
    "Officer Login Portal": "অফিসার লগইন পোর্টাল",
    "Navigation": "নেভিগেশন",
    "DWLR Telemetry Network": "ডিডব্লিউএলআর টেলিমেট্রি নেটওয়ার্ক",
    "Real-Time DWLR Groundwater Intelligence": "রিয়েল-টাইম ভূগর্ভস্থ জল বুদ্ধিমত্তা",
    "Switch Account / Role": "অ্যাকাউন্ট / ভূমিকা পরিবর্তন",
    "Explore Groundwater Map": "ভূগর্ভস্থ জল মানচিত্র অন্বেষণ",
    "Get Crop Advice": "ফসল পরামর্শ পান",
    "View Technical Evidence": "প্রযুক্তিগত প্রমাণ দেখুন",
    "Executive Water Intelligence Brief": "নির্বাহী জল সংক্ষিপ্ত বিবরণ",
    "Current Situation": "বর্তমান পরিস্থিতি",
    "Priority Risk Belt": "অগ্রাধিকার ঝুঁকি অঞ্চল",
    "30-Day Forecast": "৩০ দিনের পূর্বাভাস",
    "Recommended Action": "প্রস্তাবিত পদক্ষেপ",
    "Regional Stress Level": "আঞ্চলিক চাপের মাত্রা",
    "Critical Stations": "সংকটজনক স্টেশন",
    "Recharge Outlook": "পুনর্ভরণ দৃষ্টিভঙ্গি",
    "Confidence Score": "নির্ভরযোগ্যতা স্কোর",
    "Data Provenance": "উপাত্তের উৎস",
    "login": "লগ ইন",
    "logout": "সাইন আউট"
  },
  "te": {
    "Dashboard": "డాష్‌బోర్డ్",
    "Official Command Center": "అధికారిక కమాండ్ సెంటర్",
    "Command Center": "కమాండ్ సెంటర్",
    "Groundwater Map": "భూజల పటం",
    "Forecast & Predictions": "అంచనా & భవిష్యత్తు",
    "Anomalies & Triage": "రిస్క్ హెచ్చరికలు",
    "Anomaly Detection": "అసాధారణ తగ్గుదల గుర్తింపు",
    "Crop & Irrigation Advice": "పంట & సాగునీటి సలహా",
    "Crop Advisor": "పంట సలహాదారు",
    "Regional Analytics": "ప్రాంతీయ విశ్లేషణ",
    "WhatsApp AI Assistant": "వాట్సాప్ ఏఐ అసిస్టెంట్",
    "WhatsApp Farmer": "వాట్సాప్ రైతు సేవ",
    "Help & Knowledge Base": "సహాయ కేంద్రం",
    "Help & Knowledge": "సహాయం & సమాచారం",
    "Officer Login Portal": "అధికారుల లాగిన్ పోర్టల్",
    "Navigation": "నావిగేషన్",
    "DWLR Telemetry Network": "DWLR టెలిమెట్రీ నెట్‌వర్క్",
    "Real-Time DWLR Groundwater Intelligence": "నిజ-సమయ భూజల సమాచారం",
    "Switch Account / Role": "ఖాతా / పాత్ర మార్చు",
    "Explore Groundwater Map": "భూజల పటాన్ని చూడండి",
    "Get Crop Advice": "పంట సలహా పొందండి",
    "View Technical Evidence": "సాంకేతిక ఆధారాలు చూడండి",
    "Executive Water Intelligence Brief": "ఎగ్జిక్యూటివ్ వాటర్ ఇంటెలిజెన్స్ బ్రీఫ్",
    "Current Situation": "ప్రస్తుత పరిస్థితి",
    "Priority Risk Belt": "ప్రాధాన్యతా ప్రమాద ప్రాంతం",
    "30-Day Forecast": "30-రోజుల సూచన",
    "Recommended Action": "సిఫార్సు చేసిన చర్య",
    "Regional Stress Level": "ప్రాంతీయ ఒత్తిడి స్థాయి",
    "Critical Stations": "కీలక కేంద్రాలు",
    "Recharge Outlook": "రీఛార్జ్ ఔట్‌లుక్",
    "Confidence Score": "విశ్వసనీయత స్కోరు",
    "Data Provenance": "డేటా మూలం",
    "login": "లాగిన్",
    "logout": "సైన్ అవుట్"
  },
  "mr": {
    "Dashboard": "डॅशबोर्ड",
    "Official Command Center": "अधिकृत कमांड सेंटर",
    "Command Center": "कमांड सेंटर",
    "Groundwater Map": "भूजल नकाशा",
    "Forecast & Predictions": "पूर्वानुमान व अंदाज",
    "Anomalies & Triage": "धोका इशारे",
    "Anomaly Detection": "असामान्य घट ओळख",
    "Crop & Irrigation Advice": "पीक व सिंचन सल्ला",
    "Crop Advisor": "पीक सल्लागार",
    "Regional Analytics": "प्रादेशिक विश्लेषण",
    "WhatsApp AI Assistant": "व्हॉट्सॲप एआय सहाय्यक",
    "WhatsApp Farmer": "व्हॉट्सॲप शेतकरी सेवा",
    "Help & Knowledge Base": "मदत व माहिती केंद्र",
    "Help & Knowledge": "मदत व माहिती",
    "Officer Login Portal": "अधिकारी लॉगिन पोर्टल",
    "Navigation": "नेव्हिगेशन",
    "DWLR Telemetry Network": "DWLR टेलिमेट्री नेटवर्क",
    "Real-Time DWLR Groundwater Intelligence": "रिअल-टाइम भूजल बुद्धिमत्ता",
    "Switch Account / Role": "खाते / भूमिका बदला",
    "Explore Groundwater Map": "भूजल नकाशा पहा",
    "Get Crop Advice": "पीक सल्ला मिळवा",
    "View Technical Evidence": "तांत्रिक पुरावे पहा",
    "Executive Water Intelligence Brief": "कार्यकारी जल गुप्तवार्ता संक्षिप्त",
    "Current Situation": "सद्यस्थिती",
    "Priority Risk Belt": "प्राधान्य जोखीम पट्टा",
    "30-Day Forecast": "३०-दिवसीय अंदाज",
    "Recommended Action": "शिफारस केलेली कृती",
    "Regional Stress Level": "प्रादेशिक ताण पातळी",
    "Critical Stations": "गंभीर स्टेशन्स",
    "Recharge Outlook": "पुनर्भरण दृष्टिकोन",
    "Confidence Score": "विश्वासार्हता धावसंख्या",
    "Data Provenance": "डेटा स्रोत",
    "login": "लॉग इन",
    "logout": "साइन आउट"
  },
  "ta": {
    "Dashboard": "டாஷ்போர்டு",
    "Official Command Center": "அதிகாரப்பூர்வ கட்டளை மையம்",
    "Command Center": "கட்டளை மையம்",
    "Groundwater Map": "நிலத்தடி நீர் வரைபடம்",
    "Forecast & Predictions": "முன்னறிவிப்பு & கணிப்புகள்",
    "Anomalies & Triage": "அபாய எச்சரிக்கைகள்",
    "Anomaly Detection": "இயல்பற்ற வீழ்ச்சி கண்டறிதல்",
    "Crop & Irrigation Advice": "பயிர் & பாசன ஆலோசனை",
    "Crop Advisor": "பயிர் ஆலோசகர்",
    "Regional Analytics": "பிராந்திய பகுப்பாய்வு",
    "WhatsApp AI Assistant": "வாட்ஸ்அப் ஏஐ உதவியாளர்",
    "WhatsApp Farmer": "வாட்ஸ்அப் விவசாயி சேவை",
    "Help & Knowledge Base": "உதவி & அறிவு மையம்",
    "Help & Knowledge": "உதவி & மையம்",
    "Officer Login Portal": "அதிகாரி உள்நுழைவு தளம்",
    "Navigation": "வழிசெலுத்தல்",
    "DWLR Telemetry Network": "DWLR டெலிமெட்ரி நெட்வொர்க்",
    "Real-Time DWLR Groundwater Intelligence": "நிகழ்நேர நிலத்தடி நீர் நுண்ணறிவு",
    "Switch Account / Role": "கணக்கு / பங்கை மாற்றவும்",
    "Explore Groundwater Map": "நிலத்தடி நீர் வரைபடத்தை ஆராய்க",
    "Get Crop Advice": "பயிர் ஆலோசனை பெறுக",
    "View Technical Evidence": "தொழில்நுட்ப ஆதாரத்தைக் காண்க",
    "Executive Water Intelligence Brief": "நிர்வாக நீர் புலனாய்வு சுருக்கம்",
    "Current Situation": "தற்போதைய நிலை",
    "Priority Risk Belt": "முன்னுரிமை ஆபத்து மண்டலம்",
    "30-Day Forecast": "30-நாள் முன்னறிவிப்பு",
    "Recommended Action": "பரிந்துரைக்கப்பட்ட நடவடிக்கை",
    "Regional Stress Level": "பிராந்திய அழுத்த நிலை",
    "Critical Stations": "முக்கிய நிலையங்கள்",
    "Recharge Outlook": "மறுஊட்டப் பார்வை",
    "Confidence Score": "நம்பகத்தன்மை மதிப்பீடு",
    "Data Provenance": "தரவு ஆதாரம்",
    "login": "உள்நுழைக",
    "logout": "வெளியேறுக"
  },
  "gu": {
    "Dashboard": "ડેશબોર્ડ",
    "Official Command Center": "સત્તાવાર કમાન્ડ સેન્ટર",
    "Command Center": "કમાન્ડ સેન્ટર",
    "Groundwater Map": "ભૂગર્ભજળ નકશો",
    "Forecast & Predictions": "પૂર્વાનુમાન અને અંદાજ",
    "Anomalies & Triage": "જોખમ ચેતવણીઓ",
    "Anomaly Detection": "અસામાન્ય ઘટાડો ઓળખ",
    "Crop & Irrigation Advice": "પાક અને સિંચાઈ સલાહ",
    "Crop Advisor": "પાક સલાહકાર",
    "Regional Analytics": "પ્રાદેશિક પૃથક્કરણ",
    "WhatsApp AI Assistant": "વોટ્સએપ એઆઈ આસિસ્ટન્ટ",
    "WhatsApp Farmer": "વોટ્સએપ ખેડૂત સેવા",
    "Help & Knowledge Base": "મદદ અને જ્ઞાન કેન્દ્ર",
    "Help & Knowledge": "મદદ અને જ્ઞાન",
    "Officer Login Portal": "અધિકારી લોગિન પોર્ટલ",
    "Navigation": "નેવિગેશન",
    "DWLR Telemetry Network": "DWLR ટેલિમેટ્રી નેટવર્ક",
    "Real-Time DWLR Groundwater Intelligence": "રીઅલ-ટાઇમ ભૂગર્ભજળ બુદ્ધિ",
    "Switch Account / Role": "ખાતું / ભૂમિકા બદલો",
    "Explore Groundwater Map": "ભૂગર્ભજળ નકશો જુઓ",
    "Get Crop Advice": "પાક સલાહ મેળવો",
    "View Technical Evidence": "તકનીકી પુરાવા જુઓ",
    "Executive Water Intelligence Brief": "કાર્યકારી જળ ગુપ્તચર સંક્ષેપ",
    "Current Situation": "વર્તમાન પરિસ્થિતિ",
    "Priority Risk Belt": "અગ્રતા જોખમ ક્ષેત્ર",
    "30-Day Forecast": "30-દિવસની આગાહી",
    "Recommended Action": "ભલામણ કરેલ પગલાં",
    "Regional Stress Level": "પ્રાદેશિક તણાવ સ્તર",
    "Critical Stations": "ગંભીર સ્ટેશનો",
    "Recharge Outlook": "રિચાર્જ આઉટલૂક",
    "Confidence Score": "વિશ્વાસ સ્કોર",
    "Data Provenance": "ડેટા સ્ત્રોત",
    "login": "પ્રવેશ કરો",
    "logout": "સાઇન આઉટ"
  },
  "kn": {
    "Dashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    "Official Command Center": "ಅಧಿಕೃತ ಕಮಾಂಡ್ ಸೆಂಟರ್",
    "Command Center": "ಕಮಾಂಡ್ ಸೆಂಟರ್",
    "Groundwater Map": "ಅಂತರ್ಜಲ ನಕ್ಷೆ",
    "Forecast & Predictions": "ಮುನ್ಸೂಚನೆ ಮತ್ತು ಅಂದಾಜು",
    "Anomalies & Triage": "ಅಪಾಯ ಸೂಚನೆಗಳು",
    "Anomaly Detection": "ಅಸಹಜ ಕುಸಿತ ಪತ್ತೆ",
    "Crop & Irrigation Advice": "ಬೆಳೆ ಮತ್ತು ನೀರಾವರಿ ಸಲಹೆ",
    "Crop Advisor": "ಬೆಳೆ ಸಲಹೆಗಾರ",
    "Regional Analytics": "ಪ್ರಾದೇಶಿಕ ವಿಶ್ಲೇಷಣೆ",
    "WhatsApp AI Assistant": "ವಾಟ್ಸಾಪ್ ಎಐ ಸಹಾಯಕ",
    "WhatsApp Farmer": "ವಾಟ್ಸಾಪ್ ರೈತ ಸೇವೆ",
    "Help & Knowledge Base": "ಸಹಾಯ ಮತ್ತು ಮಾಹಿತಿ ಕೇಂದ್ರ",
    "Help & Knowledge": "ಸಹಾಯ ಮತ್ತು ಮಾಹಿತಿ",
    "Officer Login Portal": "ಅಧಿಕಾರಿ ಲಾಗಿನ್ ಪೋರ್ಟಲ್",
    "Navigation": "ನ್ಯಾವಿಗೇಷನ್",
    "DWLR Telemetry Network": "ಡಿಡಬ್ಲ್ಯುಎಲ್ಆರ್ ಟೆಲಿಮೆಟ್ರಿ ನೆಟ್‌ವರ್ಕ್",
    "Real-Time DWLR Groundwater Intelligence": "ನೈಜ-ಸಮಯದ ಅಂತರ್ಜಲ ಬುದ್ಧಿಮತ್ತೆ",
    "Switch Account / Role": "ಖಾತೆ / ಪಾತ್ರ ಬದಲಾಯಿಸಿ",
    "Explore Groundwater Map": "ಅಂತರ್ಜಲ ನಕ್ಷೆಯನ್ನು ಅನ್ವೇಷಿಸಿ",
    "Get Crop Advice": "ಬೆಳೆ ಸಲಹೆ ಪಡೆಯಿರಿ",
    "View Technical Evidence": "ತಾಂತ್ರಿಕ ಪುರಾವೆ ವೀಕ್ಷಿಸಿ",
    "Executive Water Intelligence Brief": "ಕಾರ್ಯನಿರ್ವಾಹಕ ಜಲ ಗುಪ್ತಚರ ಸಾರಾಂಶ",
    "Current Situation": "ಪ್ರಸ್ತುತ ಪರಿಸ್ಥಿತಿ",
    "Priority Risk Belt": "ಆದ್ಯತೆಯ ಅಪಾಯ ವಲಯ",
    "30-Day Forecast": "30-ದಿನಗಳ ಮುನ್ಸೂಚನೆ",
    "Recommended Action": "ಶಿಫಾರಸು ಮಾಡಿದ ಕ್ರಮ",
    "Regional Stress Level": "ಪ್ರಾದೇಶಿಕ ಒತ್ತಡದ ಮಟ್ಟ",
    "Critical Stations": "ನಿರ್ಣಾಯಕ ನಿಲ್ದಾಣಗಳು",
    "Recharge Outlook": "ರೀಚಾರ್ಜ್ ಔಟ್‌ಲುಕ್",
    "Confidence Score": "ವಿಶ್ವಾಸಾರ್ಹತೆಯ ಅಂಕ",
    "Data Provenance": "ಡೇಟಾ ಮೂಲ",
    "login": "ಲಾಗಿನ್",
    "logout": "ಸೈನ್ ಔಟ್"
  },
  "ml": {
    "Dashboard": "ഡാഷ്‌ബോർഡ്",
    "Official Command Center": "ഔദ്യോഗിക കമാൻഡ് സെന്റർ",
    "Command Center": "കമാൻഡ് സെന്റർ",
    "Groundwater Map": "ഭൂഗർഭജല ഭൂപടം",
    "Forecast & Predictions": "പ്രവചനങ്ങളും കണക്കുകൂട്ടലുകളും",
    "Anomalies & Triage": "അപായ മുന്നറിയിപ്പുകൾ",
    "Anomaly Detection": "അസാധാരണ ഇടിവ് കണ്ടെത്തൽ",
    "Crop & Irrigation Advice": "വിളയും നനയ്ക്കൽ നിർദ്ദേശവും",
    "Crop Advisor": "വിള ഉപദേഷ്ടാവ്",
    "Regional Analytics": "പ്രദേശിക വിശകലനം",
    "WhatsApp AI Assistant": "വാട്സ്ആപ്പ് എഐ അസിസ്റ്റന്റ്",
    "WhatsApp Farmer": "വാട്സ്ആപ്പ് കർഷക സേവനം",
    "Help & Knowledge Base": "സഹായ കേന്ദ്രം",
    "Help & Knowledge": "സഹായവും വിവരങ്ങളും",
    "Officer Login Portal": "ഓഫീസർ ലോഗിൻ പോർട്ടൽ",
    "Navigation": "നാവിഗേഷൻ",
    "DWLR Telemetry Network": "DWLR ടെലിമെട്രി ശൃംഖല",
    "Real-Time DWLR Groundwater Intelligence": "തത്സമയ ഭൂഗർഭജല വിവരങ്ങൾ",
    "Switch Account / Role": "അക്കൗണ്ട് / റോൾ മാറ്റുക",
    "Explore Groundwater Map": "ഭൂഗർഭജല മാപ്പ് പരിശോധിക്കുക",
    "Get Crop Advice": "വിള ഉപദേശം നേടുക",
    "View Technical Evidence": "സാങ്കേതിക തെളിവുകൾ കാണുക",
    "Executive Water Intelligence Brief": "എക്സിക്യൂട്ടീവ് വാട്ടർ ഇന്റലിജൻസ് സംഗ്രഹം",
    "Current Situation": "നിലവിലെ സാഹചര്യം",
    "Priority Risk Belt": "മുൻഗണനാ അപകട മേഖല",
    "30-Day Forecast": "30 ദിവസത്തെ പ്രവചനം",
    "Recommended Action": "ശുപാർശ ചെയ്ത നടപടി",
    "Regional Stress Level": "പ്രാദേശിക സമ്മർദ്ദ നില",
    "Critical Stations": "പ്രധാന സ്റ്റേഷനുകൾ",
    "Recharge Outlook": "റീചാർജ് കാഴ്ചപ്പാട്",
    "Confidence Score": "വിശ്വാസ്യത സ്കോർ",
    "Data Provenance": "ഡാറ്റ ഉറവിടം",
    "login": "ലോഗിൻ",
    "logout": "സൈൻ ഔട്ട്"
  },
  "pa": {
    "Dashboard": "ਡੈਸ਼ਬੋਰਡ",
    "Official Command Center": "ਅਧਿਕਾਰਤ ਕਮਾਂਡ ਸੈਂਟਰ",
    "Command Center": "ਕਮਾਂਡ ਸੈਂਟਰ",
    "Groundwater Map": "ਭੂਮੀਗਤ ਜਲ ਨਕਸ਼ਾ",
    "Forecast & Predictions": "ਭਵਿੱਖਬਾਣੀ ਅਤੇ ਅਨੁਮਾਨ",
    "Anomalies & Triage": "ਜੋਖਮ ਚੇਤਾਵਨੀਆਂ",
    "Anomaly Detection": "ਅਸਧਾਰਨ ਗਿਰਾਵਟ ਪਛਾਣ",
    "Crop & Irrigation Advice": "ਫਸਲ ਅਤੇ ਸਿੰਚਾਈ ਸਲਾਹ",
    "Crop Advisor": "ਫਸਲ ਸਲਾਹਕਾਰ",
    "Regional Analytics": "ਖੇਤਰੀ ਵਿਸ਼ਲੇਸ਼ਣ",
    "WhatsApp AI Assistant": "ਵਟਸਐਪ ਏਆਈ ਸਹਾਇਕ",
    "WhatsApp Farmer": "ਵਟਸਐਪ ਕਿਸਾਨ ਸੇਵਾ",
    "Help & Knowledge Base": "ਮਦਦ ਅਤੇ ਜਾਣਕਾਰੀ ਕੇਂਦਰ",
    "Help & Knowledge": "ਮਦਦ ਅਤੇ ਜਾਣਕਾਰੀ",
    "Officer Login Portal": "ਅਧਿਕਾਰੀ ਲੌਗਇਨ ਪੋਰਟਲ",
    "Navigation": "ਨੇਵੀਗੇਸ਼ਨ",
    "DWLR Telemetry Network": "DWLR ਟੈਲੀਮੈਟਰੀ ਨੈੱਟਵਰਕ",
    "Real-Time DWLR Groundwater Intelligence": "ਰੀਅਲ-ਟਾਈਮ ਭੂਮੀਗਤ ਪਾਣੀ ਬੁੱਧੀ",
    "Switch Account / Role": "ਖਾਤਾ / ਭੂਮਿਕਾ ਬਦਲੋ",
    "Explore Groundwater Map": "ਭੂਮੀਗਤ ਜਲ ਨਕਸ਼ਾ ਦੇਖੋ",
    "Get Crop Advice": "ਫ਼ਸਲ ਸਲਾਹ ਲਵੋ",
    "View Technical Evidence": "ਤਕਨੀਕੀ ਸਬੂਤ ਦੇਖੋ",
    "Executive Water Intelligence Brief": "ਕਾਰਜਕਾਰੀ ਜਲ ਖੁਫੀਆ ਸੰਖੇਪ",
    "Current Situation": "ਮੌਜੂਦਾ ਸਥਿਤੀ",
    "Priority Risk Belt": "ਤਰਜੀਹੀ ਜੋਖਮ ਖੇਤਰ",
    "30-Day Forecast": "30-ਦਿਨਾਂ ਦੀ ਭਵਿੱਖਬਾਣੀ",
    "Recommended Action": "ਸਿਫ਼ਾਰਸ਼ ਕੀਤੀ ਕਾਰਵਾਈ",
    "Regional Stress Level": "ਖੇਤਰੀ ਤਣਾਅ ਦਾ ਪੱਧਰ",
    "Critical Stations": "ਨਾਜ਼ੁਕ ਸਟੇਸ਼ਨ",
    "Recharge Outlook": "ਰੀਚਾਰਜ ਆਉਟਲੁੱਕ",
    "Confidence Score": "ਭਰੋਸੇਯੋਗਤਾ ਸਕੋਰ",
    "Data Provenance": "ਡੇਟਾ ਸਰੋਤ",
    "login": "ਲਾਗਇਨ",
    "logout": "ਸਾਈਨ ਆਉਟ"
  },
  "or": {
    "Dashboard": "ଡ୍ୟାସବୋର୍ଡ",
    "Official Command Center": "ଅଫିସିଆଲ୍ କମାଣ୍ଡ ସେଣ୍ଟର",
    "Command Center": "କମାଣ୍ଡ ସେଣ୍ଟର",
    "Groundwater Map": "ଭୂତଳ ଜଳ ମାନଚିତ୍ର",
    "Forecast & Predictions": "ପୂର୍ବାନୁମାନ ଓ ଆକଳନ",
    "Anomalies & Triage": "ବିପଦ ଚେତାବନୀ",
    "Anomaly Detection": "ଅସ୍ୱାଭାବିକ ହ୍ରାସ ଚିହ୍ନଟ",
    "Crop & Irrigation Advice": "ଫସଲ ଓ ଜଳସେଚନ ପରାମର୍ଶ",
    "Crop Advisor": "ଫସଲ ପରାମର୍ଶଦାତା",
    "Regional Analytics": "ଆଞ୍ଚଳିକ ବିଶ୍ଳେଷଣ",
    "WhatsApp AI Assistant": "ହ୍ୱାଟସଆପ ଏଆଇ ସହାୟକ",
    "WhatsApp Farmer": "ହ୍ୱାଟସଆପ କୃଷକ ସେବା",
    "Help & Knowledge Base": "ସାହାଯ୍ୟ ଓ ତଥ୍ୟ କେନ୍ଦ୍ର",
    "Help & Knowledge": "ସାହାଯ୍ୟ ଓ ତଥ୍ୟ",
    "Officer Login Portal": "ଅଧିକାରୀ ଲଗଇନ୍ ପୋର୍ଟାଲ୍",
    "Navigation": "ନାଭିଗେସନ୍",
    "DWLR Telemetry Network": "DWLR ଟେଲିମେଟ୍ରି ନେଟୱାର୍କ",
    "Real-Time DWLR Groundwater Intelligence": "ରିଅଲ-ଟାଇମ୍ ଭୂତଳ ଜଳ ଗୁପ୍ତଚର",
    "Switch Account / Role": "ଖାତା / ଭୂମିକା ପରିବର୍ତ୍ତନ କରନ୍ତୁ",
    "Explore Groundwater Map": "ଭୂତଳ ଜଳ ମାନଚିତ୍ର ଦେଖନ୍ତୁ",
    "Get Crop Advice": "ଫସଲ ପରାମର୍ଶ ପାଆନ୍ତୁ",
    "View Technical Evidence": "ବୈଷୟିକ ପ୍ରମାଣ ଦେଖନ୍ତୁ",
    "Executive Water Intelligence Brief": "କାର୍ଯ୍ୟନିର୍ବାହୀ ଜଳ ଗୁପ୍ତଚର ସଂକ୍ଷିପ୍ତ",
    "Current Situation": "ବର୍ତ୍ତମାନର ସ୍ଥିତି",
    "Priority Risk Belt": "ପ୍ରାଥମିକତା ବିପଦ ଅଞ୍ଚଳ",
    "30-Day Forecast": "୩୦-ଦିନର ପୂର୍ବାନୁମାନ",
    "Recommended Action": "ପ୍ରସ୍ତାବିତ କାର୍ଯ୍ୟାନୁଷ୍ଠାନ",
    "Regional Stress Level": "ଆଞ୍ଚଳିକ ଚାପ ସ୍ତର",
    "Critical Stations": "ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ ଷ୍ଟେସନ",
    "Recharge Outlook": "ରିଚାର୍ଜ ଆଉଟଲୁକ୍",
    "Confidence Score": "ବିଶ୍ୱସନୀୟତା ସ୍କୋର",
    "Data Provenance": "ତଥ୍ୟ ଉତ୍ସ",
    "login": "ଲଗଇନ୍",
    "logout": "ସାଇନ୍ ଆଉଟ୍"
  },
  "as": {
    "Dashboard": "ড্যাশবোর্ড",
    "Official Command Center": "অফিচিয়েল কমাণ্ড চেণ্টাৰ",
    "Command Center": "কমাণ্ড চেণ্টাৰ",
    "Groundwater Map": "ভূগৰ্ভস্থ পানীৰ মানচিত্ৰ",
    "Forecast & Predictions": "পূৰ্বানুমান আৰু অনুমান",
    "Anomalies & Triage": "আশংকা সকীয়নি",
    "Anomaly Detection": "অস্বাভাৱিক হ্ৰাস চিনাক্তকৰণ",
    "Crop & Irrigation Advice": "শস্য আৰু জলসিঞ্চন পৰামৰ্শ",
    "Crop Advisor": "শস্য পৰামৰ্শদাতা",
    "Regional Analytics": "আঞ্চলিক বিশ্লেষণ",
    "WhatsApp AI Assistant": "হোৱাটছএপ এআই সহায়ক",
    "WhatsApp Farmer": "হোৱাটছএপ কৃষক সেৱা",
    "Help & Knowledge Base": "সহায় আৰু তথ্য কেন্দ্ৰ",
    "Help & Knowledge": "সহায় আৰু তথ্য",
    "Officer Login Portal": "বিষয়া লগইন প’ৰ্টেল",
    "Navigation": "নেভিগেচন",
    "DWLR Telemetry Network": "DWLR টেলিমেট্ৰি নেটৱৰ্ক",
    "Real-Time DWLR Groundwater Intelligence": "ৰিয়েল-টাইম ভূগৰ্ভস্থ পানী বুদ্ধিমত্তা",
    "Switch Account / Role": "একাউণ্ট / ভূমিকা সলনি কৰক",
    "Explore Groundwater Map": "ভূগৰ্ভস্থ পানীৰ মানচিত্ৰ চাওক",
    "Get Crop Advice": "শস্য পৰামৰ্শ লাভ কৰক",
    "View Technical Evidence": "কাৰিকৰী প্ৰমাণ চাওক",
    "Executive Water Intelligence Brief": "কাৰ্যবাহী জল তথ্য সংক্ষেপ",
    "Current Situation": "বৰ্তমান পৰিস্থিতি",
    "Priority Risk Belt": "অগ্ৰাধিকাৰ বিপদ মণ্ডল",
    "30-Day Forecast": "৩০ দিনৰ পূৰ্বানুমান",
    "Recommended Action": "পৰামৰ্শিত পদক্ষেপ",
    "Regional Stress Level": "আঞ্চলিক চাপৰ স্তৰ",
    "Critical Stations": "সংকটজনক ষ্টেচনসমূহ",
    "Recharge Outlook": "পুনৰ্ভৰণ দৃষ্টিভংগী",
    "Confidence Score": "বিশ্বাসযোগ্যতা স্কোৰ",
    "Data Provenance": "তথ্যৰ উৎস",
    "login": "লগ ইন",
    "logout": "ছাইন আউট"
  },
  "ur": {
    "Dashboard": "ڈیش بورڈ",
    "Official Command Center": "آفیشل کمانڈ سینٹر",
    "Command Center": "کمانڈ سینٹر",
    "Groundwater Map": "زیر زمین پانی کا نقشہ",
    "Forecast & Predictions": "پیشگوئی اور تخمینے",
    "Anomalies & Triage": "خطرے کی تنبیہات",
    "Anomaly Detection": "غیر معمولی کمی کی نشاندہی",
    "Crop & Irrigation Advice": "فصل اور آبپاشی کی ہدایت",
    "Crop Advisor": "فصل کا مشیر",
    "Regional Analytics": "علاقائی تجزیہ",
    "WhatsApp AI Assistant": "واٹس ایپ اے آئی اسسٹنٹ",
    "WhatsApp Farmer": "واٹس ایپ کسان سروس",
    "Help & Knowledge Base": "مدد اور معلومات مرکز",
    "Help & Knowledge": "مدد اور معلومات",
    "Officer Login Portal": "آفیسر لاگ ان پورٹل",
    "Navigation": "رہنمائی",
    "DWLR Telemetry Network": "ڈی ڈبلیو ایل آر ٹیلی میٹری نیٹ ورک",
    "Real-Time DWLR Groundwater Intelligence": "حقیقی وقت میں زیر زمین پانی کی معلومات",
    "Switch Account / Role": "اکاؤنٹ / کردار تبدیل کریں",
    "Explore Groundwater Map": "زیر زمین پانی کا نقشہ دیکھیں",
    "Get Crop Advice": "فصل کا مشورہ حاصل کریں",
    "View Technical Evidence": "تکنیکی ثبوت دیکھیں",
    "Executive Water Intelligence Brief": "ایگزیکٹو واٹر انٹیلی جنس بریف",
    "Current Situation": "موجودہ صورتحال",
    "Priority Risk Belt": "ترجیحی خطرے کا خطہ",
    "30-Day Forecast": "30 دن کی پیشگوئی",
    "Recommended Action": "تجویز کردہ عمل",
    "Regional Stress Level": "علاقائی دباؤ کی سطح",
    "Critical Stations": "اہم اسٹیشنز",
    "Recharge Outlook": "ریچارج آؤٹ لک",
    "Confidence Score": "اعتمادی اسکور",
    "Data Provenance": "ڈیٹا کا ماخذ",
    "login": "لاگ ان",
    "logout": "سائن آؤٹ"
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguageState] = useState<string>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('jalkrishi_language');
      if (saved && SUPPORTED_LANGUAGES.some((l) => l.code === saved)) {
        return saved;
      }
    }
    return 'en';
  });

  const languageConfig =
    SUPPORTED_LANGUAGES.find((l) => l.code === currentLanguage) || SUPPORTED_LANGUAGES[0];

  const setLanguage = (code: string) => {
    setCurrentLanguageState(code);
    const target = SUPPORTED_LANGUAGES.find((l) => l.code === code);
    const dir = target?.dir || 'ltr';

    if (typeof document !== 'undefined') {
      document.documentElement.dir = dir;
      document.documentElement.lang = code;
    }
    if (typeof window !== 'undefined') {
      localStorage.setItem('jalkrishi_language', code);
    }
  };

  useEffect(() => {
    setLanguage(currentLanguage);
  }, []);

  const tFunc = (key: any): string => {
    if (!key) return '';
    const strKey = String(key);

    // 1. Check UI_DICTIONARIES for exact navigation / header UI key string
    const targetUiDict = UI_DICTIONARIES[currentLanguage] || UI_DICTIONARIES['en'];
    if (targetUiDict && targetUiDict[strKey]) {
      return targetUiDict[strKey];
    }

    // 2. Check i18n t() resolver for standard TranslationKey
    const i18nResult = tI18n(strKey as TranslationKey, currentLanguage);
    if (i18nResult && i18nResult !== strKey) {
      return i18nResult;
    }

    // 3. Fall back to English UI dictionary or raw key string
    return UI_DICTIONARIES['en']?.[strKey] || strKey;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, languageConfig, t: tFunc }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

